/* text/Program_description.js */

const programData = {
  "accounting_operations": {
    "name": "Accounting Operations",
    "sector": "Business",
    "lexile": "1180L–1280L",
    "lexile_mid": 1230,
    "grade_band": "12.2",
    "cognitive_load": "Medium",
    "fast_ela": "Level 4 (proficient–strong)",
    "act": "20–22",
    "sat": "500–550",
    "barrier_pct": "30–40%",
    "workforce_rating": 5,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Interpreting procedural and regulatory texts that rely on precise terminology, sequential logic, and numerical accuracy.",
    "learning_profile": "Detail-oriented, analytical learners who prefer clear rules, definitions, and step-by-step explanations. Students who enjoy math-adjacent thinking and structured processes tend to excel.",
    "instructional_implications": "Students may focus on individual definitions but fail to connect how equity, retained earnings, and capital changes interact across financial statements. Model sequential accounting logic and connect text to numerical examples.",
    "strategies": ["Frayer Model Vocabulary Cards", "Flowcharting equity change steps", "Think-Aloud Modeling with financial statements", "Guided Annotation of cause-and-effect phrases", "Paired Explanation using real/simulated business examples"],
    "text_source": "Accredited Business Accountant Prep Course (Equity & Retained Earnings section)",
    "placement": "Text is dense with financial terminology and sequential logic. Learners must interpret multi-step accounting processes. Reading requires precision with abstract concepts.",
    "image": "images/accounting_operations.jpg",
    "sample_image": "images/Program_Text_Examples_images/Accounting_Operations_1.png, images/Program_Text_Examples_images/Accounting_Operations_2.png, images/Program_Text_Examples_images/Accounting_Operations_3.png"
  },
  "applied_cybersecurity": {
    "name": "Applied Cybersecurity",
    "sector": "Information Technology",
    "lexile": "1280L–1380L",
    "lexile_mid": 1330,
    "grade_band": "11–CCR",
    "cognitive_load": "High",
    "fast_ela": "Level 4 (high)",
    "act": "25–27",
    "sat": "570–610",
    "barrier_pct": "70–80%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "High Gap",
    "main_challenge": "Decoding dense, abstract technical documentation across multiple protocols while integrating vulnerability concepts, tools, and multi-step logic.",
    "learning_profile": "Analytical, systems-oriented learners who enjoy logic, pattern recognition, and understanding how components interact. Strong in procedural thinking but may struggle with conceptual depth.",
    "instructional_implications": "Break down API flows with diagrams; chunk long documentation; explicitly teach how to read standards and specifications; model error interpretation; scaffold vocabulary.",
    "strategies": ["Dual Coding (flow diagrams + text)", "Annotation Routines", "Vocabulary Clustering", "Logic Retell ('explain step-by-step')", "Error-Analysis Walkthroughs", "Worked-Example Comparisons", "Chunking Long Passages", "Prediction Prompts before executing a test"],
    "text_source": "OWASP Web Security Testing Guide; API security chapters",
    "placement": "Best suited for students who can follow multi-step procedures, interpret structured text (JSON/XML), persist through troubleshooting, and reason about cause-and-effect.",
    "image": "images/applied_cybersecurity.jpg",
    "sample_image": "images/Program_Text_Examples_images/Applied_Cybersecurity_1.png, images/Program_Text_Examples_images/Applied_Cybersecurity_2.png, images/Program_Text_Examples_images/Applied_Cybersecurity_3.png"
  },
  "auto_collision": {
    "name": "Automotive Collision Technology Technician",
    "sector": "Transportation",
    "lexile": "1050L–1150L",
    "lexile_mid": 1100,
    "grade_band": "10.5",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "25–35%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Reading embedded in procedural manuals, repair estimates, OEM specifications. Must interpret step-by-step repair instructions, diagrams, material specifications, and conditional statements.",
    "learning_profile": "Procedural, hands-on learners who connect reading to immediate action; thrive when written instructions are paired with demonstration or repair tasks.",
    "instructional_implications": "Students may read reactively — searching for 'what to do' but overlooking diagnostic reasoning ('why it happened'). Instruction should emphasize the causal logic of the text.",
    "strategies": ["Error Analysis Charts (defect → cause → cure)", "Color-Coded Reading of cause vs. correction", "Paired Reading with Demonstration", "'Explain the Fix' Reflections"],
    "text_source": "ASE Certification Prep: Painting and Refinishing ASE Test B2",
    "placement": "Texts are direct and procedural but assume strong vocabulary recall. Students must distinguish between cause, symptom, and corrective action.",
    "image": "images/automotive_collision_technology_technician.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Automotive_Collision_Technology_1.png"
  },
  "aviation_airframe": {
    "name": "Aviation Airframe Mechanics",
    "sector": "Aviation",
    "lexile": "1280L–1420L",
    "lexile_mid": 1350,
    "grade_band": "14.2",
    "cognitive_load": "High",
    "fast_ela": "Level 4+",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "40–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Interpreting FAA regulatory language, maintenance manuals, Airworthiness Directives, and multi-step procedures written with precision and zero tolerance for ambiguity.",
    "learning_profile": "Analytical and mechanically oriented learners who enjoy understanding systems and processes; prefer structured logic, precision, and problem-solving through cause-and-effect reasoning.",
    "instructional_implications": "Reading is cognitively demanding and dense with engineering vocabulary. Instructors should pre-teach specialized terms and model how to interpret diagrams alongside text.",
    "strategies": ["Visual Scaffolds (schematics, color-coded diagrams)", "Chunking Complex Text into Procedural Steps", "Vocabulary Notebooks", "Reciprocal Teaching (students summarize process steps)"],
    "text_source": "FAA-H-8083-31B General Handbook",
    "placement": "High-density technical language, multi-step logical reasoning, and scientific vocabulary. Strong reading fluency and familiarity with scientific syntax are essential.",
    "image": "images/aviation_airframe_mechanics.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Aviation_Airframe_Mechanics_1.png, images/Program_Text_Examples_images/Aviation_Airframe_Mechanics_2.png, images/Program_Text_Examples_images/Aviation_Airframe_Mechanics_3.png"
  },
  "aviation_powerplant": {
    "name": "Aviation Powerplant Mechanics",
    "sector": "Aviation",
    "lexile": "1280L–1420L",
    "lexile_mid": 1350,
    "grade_band": "14.2",
    "cognitive_load": "High",
    "fast_ela": "Level 4 or higher",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "45–60%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Dense, technical, precision-oriented texts combining mechanical theory with regulatory and procedural documentation. Must interpret FAA-approved engine manuals with exact language and conditional logic.",
    "learning_profile": "Analytical and mechanically oriented learners who enjoy understanding systems and processes; prefer structured logic, precision, and problem-solving through cause-and-effect reasoning.",
    "instructional_implications": "Reading is cognitively demanding and dense with engineering vocabulary. Instructors should pre-teach specialized terms and model how to interpret diagrams alongside text.",
    "strategies": ["Visual Scaffolds (schematics, color-coded diagrams)", "Chunking Complex Text into Procedural Steps", "Vocabulary Notebooks", "Reciprocal Teaching (students summarize process steps)"],
    "text_source": "FAA 8083 AMT Powerplant Handbook",
    "placement": "Heavy concentration of technical terminology, schematic interpretation, and FAA regulatory language. Students with limited aviation background may need vocabulary scaffolds.",
    "image": "images/aviation_powerplant_mechanics.jpg",
    "sample_image": "images/Program_Text_Examples_images/Aviation_Powerplant_Mechanics_1.png, images/Program_Text_Examples_images/Aviation_Powerplant_Mechanics_2.png, images/Program_Text_Examples_images/Aviation_Powerplant_Mechanics_3.png"
  },
  "avionics": {
    "name": "Avionics Systems Technician",
    "sector": "Aviation",
    "lexile": "1220L–1340L",
    "lexile_mid": 1280,
    "grade_band": "12.8",
    "cognitive_load": "High",
    "fast_ela": "Level 4+",
    "act": "22–25",
    "sat": "560–610",
    "barrier_pct": "45–60%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Texts blend dense technical documentation with abstract systems thinking. Must interpret wiring diagrams, logic schematics, installation manuals, and FAA regulatory language.",
    "learning_profile": "Systems-oriented, analytical learners who process information best through structured visuals, flow diagrams, and real-world analogies.",
    "instructional_implications": "Abstract and cumulative reading demands. Misreading small text cues leads to conceptual errors.",
    "strategies": ["Interactive Diagram Labeling", "Stepwise Summarization", "Guided Vocabulary Logs with Visuals", "Reciprocal Questioning to connect theory to system behavior"],
    "text_source": "Avionics: Beyond the AET (Iridium and Transmitter Systems)",
    "placement": "Texts are dense and informational, demanding integration of electronic theory, systems diagrams, and mathematical reasoning.",
    "image": "images/avionics_systems_technician.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Avionics_Systems_Technician_1.png, images/Program_Text_Examples_images/Avionics_Systems_Technician_2.png, images/Program_Text_Examples_images/Avionics_Systems_Technician_3.png"
  },
  "building_construction": {
    "name": "Building Construction Technologies",
    "sector": "Construction",
    "lexile": "1080L–1200L",
    "lexile_mid": 1140,
    "grade_band": "10.8",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "30–40%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Texts combine technical explanations, building codes, safety regulations, and procedural instructions. Must interpret construction drawings, material specifications, and conditional language in codes.",
    "learning_profile": "Procedural-analytical learners who like clear rules, visual references, and predictable structure; benefit from examples and real-world applications tied to building tasks.",
    "instructional_implications": "Text integrates math with procedural explanations. Some learners will need help with language around formulas and code references.",
    "strategies": ["Math-to-Text Translation", "Applied Reading Walkthroughs", "Structured Word Walls (technical + math terms)", "Think-Aloud Modeling for interpreting specifications"],
    "text_source": "NCCER Construction Technology, Pearson (Section 4.0.0 Stair Calculations)",
    "placement": "The text blends technical vocabulary, procedural language, and applied math. Strong contextual clues make it readable with moderate scaffolding.",
    "image": "images/building_construction_technologies.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Building_Construction_Technology_1.png, images/Program_Text_Examples_images/Building_Construction_Technology_2.png, images/Program_Text_Examples_images/Building_Construction_Technology_3.png"
  },
  "csit": {
    "name": "Computer Systems & Information Technology",
    "sector": "Information Technology",
    "lexile": "1180L–1320L",
    "lexile_mid": 1250,
    "grade_band": "11–12",
    "cognitive_load": "High",
    "fast_ela": "Level 4 or 5",
    "act": "22–25",
    "sat": "560–620",
    "barrier_pct": "45–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Dense technical prose combining abstract networking concepts, vendor-specific terminology, protocol acronyms, and multi-step procedural instructions with command-line output interpretation.",
    "learning_profile": "Analytical, detail-oriented learners comfortable with abstract systems, symbolic representations, and rule-based logic.",
    "instructional_implications": "Instruction must deliberately bridge conceptual understanding and procedural execution. Without explicit attention to reading comprehension, students may memorize configurations without understanding system behavior.",
    "strategies": ["Concept-Mapping of Protocols", "Guided Annotation of Configuration Rules", "Acronym Decoding Routines", "Diagram-to-Text Translation Activities", "Structured Compare-and-Contrast Reading"],
    "text_source": "Cisco-aligned networking curriculum (EtherChannel, PAgP, LACP, Flex Links)",
    "placement": "Best suited for students with solid foundational reading skills who can sustain attention through dense technical explanations.",
    "image": "images/computer_systems_information_technology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Computer_Systems_&_Information_Technology_1.png, images/Program_Text_Examples_images/Computer_Systems_&_Information_Technology_2.png, images/Program_Text_Examples_images/Computer_Systems_&_Information_Technology_3.png"
  },
  "cosmetology": {
    "name": "Cosmetology",
    "sector": "Health & Beauty",
    "lexile": "1120L–1250L",
    "lexile_mid": 1185,
    "grade_band": "11.8",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "25–35%",
    "workforce_rating": 3,
    "risk": "Medium",
    "fldoe_min": "Grade 8",
    "gap": "Moderate Gap",
    "main_challenge": "Texts blend scientific concepts (anatomy of hair and skin, chemistry of products), state laws, sanitation regulations, and step-by-step procedural instructions.",
    "learning_profile": "Visual and kinesthetic learners who absorb information best through modeling, repetition, and immediate hands-on application; often strong in aesthetic perception and procedural memory.",
    "instructional_implications": "Text combines scientific, procedural, and regulatory content. Learners may understand steps but miss conceptual depth behind them.",
    "strategies": ["Demonstration-to-Text Linking", "Annotated Visuals", "Paired Reading and Practice", "Concept Mapping of chemical and anatomical terms"],
    "text_source": "Milady 2023",
    "placement": "Texts include anatomy, chemistry of hair and skin, sanitation laws, and procedural guides with specialized but familiar vocabulary.",
    "image": "images/cosmetology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Cosmetology_1.png, images/Program_Text_Examples_images/Cosmetology_2.png, images/Program_Text_Examples_images/Cosmetology_3.png"
  },
  "database_programming": {
    "name": "Database Application Development & Programming",
    "sector": "Information Technology",
    "lexile": "1180L–1280L",
    "lexile_mid": 1230,
    "grade_band": "11–CCR",
    "cognitive_load": "High",
    "fast_ela": "Level 4",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "45–60%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Severe Gap",
    "main_challenge": "Interpreting abstract, logic-dense material across multiple formats: SQL queries, programming documentation, schema diagrams, API references, and error messages.",
    "learning_profile": "Analytical, system-focused learners who like breaking problems down and experimenting. Typically strong with procedure but may need support with abstractions.",
    "instructional_implications": "Students may copy code without understanding the logic behind it. Instruction should emphasize prediction, debugging reasoning, and explaining cause-and-effect within code execution.",
    "strategies": ["Code Annotation", "Flowchart Construction", "Dual Coding (syntax + visual)", "Logic Retell", "Worked-Example Comparison", "Technical Vocabulary Mapping", "Prediction Prompts before execution", "Think-Aloud Debugging", "Structured Error-Analysis Routines"],
    "text_source": "Database fundamentals, SQL syntax, programming documentation",
    "placement": "Best suited for students with solid reading fluency, strong sequential reasoning, and comfort with logic-based tasks.",
    "image": "images/database_application_development_programming.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Database_Application_Development_&_Programming_1.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_2.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_3.gif, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_4.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_5.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_6.gif, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_7.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_8.png, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_9.gif, images/Program_Text_Examples_images/Database_Application_Development_&_Programming_10.png"
  },
  "dental_assisting": {
    "name": "Dental Assisting",
    "sector": "Healthcare",
    "lexile": "1120L–1250L",
    "lexile_mid": 1185,
    "grade_band": "11.6",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "35–50%",
    "workforce_rating": 4,
    "risk": "Medium–High",
    "fldoe_min": "Grade 10",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Texts integrate applied science (radiation physics, anatomy, infection control), procedural instructions, and regulatory language.",
    "learning_profile": "Detail-oriented learners comfortable following precise steps; thrive on visual aids and clear procedural models; often strong in pattern recognition and manual coordination.",
    "instructional_implications": "Requires interpreting scientific text with embedded physics and anatomy. Students often read at the surface level and need guided inference on 'why' behind each step.",
    "strategies": ["Chunked Guided Reading", "Annotated Diagrams", "Keyword Highlighting", "Instructor-Led Think-Pair-Share for applied comprehension"],
    "text_source": "Modern Dental Assisting, 14th Edition (X-ray Production excerpt)",
    "placement": "Ideal for students who can visualize mechanical processes and tolerate technical vocabulary.",
    "image": "images/dental_assisting.jpg",
    "sample_image": "images/Program_Text_Examples_images/Dental_Assisting_1.png, images/Program_Text_Examples_images/Dental_Assisting_2.png, images/Program_Text_Examples_images/Dental_Assisting_3.png"
  },
  "digital_media": {
    "name": "Digital Media / Multimedia Design",
    "sector": "Arts & Communications",
    "lexile": "1050L–1180L",
    "lexile_mid": 1115,
    "grade_band": "10–12",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3.5–4.0+",
    "act": "20–23",
    "sat": "500–560",
    "barrier_pct": "20–30%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Low to Moderate Gap",
    "main_challenge": "Synthesizing written instructions with visual, technical, and creative decision-making. Interpreting design briefs, technical tool guidance, and software workflows.",
    "learning_profile": "Visual, creative problem-solvers who benefit from seeing how structure affects design and functionality. Strong in hands-on exploration but may struggle to generalize rules from examples.",
    "instructional_implications": "Students may memorize tag usage without understanding why certain structures matter. Instruction should emphasize purpose, prediction, and reasoning.",
    "strategies": ["Code Annotation", "Dual Coding (markup + render view)", "Purpose Tagging ('what this element does')", "Think-Aloud Modeling", "Worked-Example Comparisons", "Structured Retell of Process Flow", "Keyword-Purpose Mapping"],
    "text_source": "Instructor-created instructional materials (Pete DiMaria)",
    "placement": "Best suited for students with moderate-to-strong reading fluency who can follow step sequences and recognize patterns.",
    "image": "images/digital_media_multimedia_design.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Digital_Media_1.png, images/Program_Text_Examples_images/Digital_Media_2.png, images/Program_Text_Examples_images/Digital_Media_3.png"
  },
  "drafting": {
    "name": "Drafting",
    "sector": "Construction",
    "lexile": "1050L–1150L",
    "lexile_mid": 1100,
    "grade_band": "10.4",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "30–40%",
    "workforce_rating": 4,
    "risk": "Medium–High",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Reading demands tightly integrated with visual-spatial interpretation. Students must decode concise technical language, symbols, annotations, and industry conventions while interpreting drawings.",
    "learning_profile": "Visual-spatial learners who think in images, proportions, and design structures; prefer blending artistic creativity with technical precision.",
    "instructional_implications": "Reading alternates between abstract concepts and highly concrete visuals. Students need help toggling between proportional reasoning and text explanations.",
    "strategies": ["Spatial Reading Strategies", "Paired Sketch-and-Summarize", "Caption Writing for Diagrams", "Interactive Scale Exercises"],
    "text_source": "Architectural Graphics, Francis D.K. Ching, 7th Edition",
    "placement": "Accessible language but cognitively demanding due to the density of illustrations and dual-coding of information.",
    "image": "images/drafting.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Drafting_1.png, images/Program_Text_Examples_images/Drafting_2.png, images/Program_Text_Examples_images/Drafting_3.png"
  },
  "early_childhood": {
    "name": "Early Childhood Education",
    "sector": "Education",
    "lexile": "1040L–1180L",
    "lexile_mid": 1110,
    "grade_band": "10.2–12.0",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "30–40%",
    "workforce_rating": 4,
    "risk": "Medium–High",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Synthesizing abstract developmental concepts with real-world classroom scenarios while interpreting nuanced guidance rather than procedural text.",
    "learning_profile": "Reflective, empathetic learners who engage deeply with human behavior, relationships, and developmental patterns; comfortable analyzing case studies.",
    "instructional_implications": "Students may default to intuitive interpretations rather than grounding conclusions in developmental principles.",
    "strategies": ["Chunked Theory-to-Practice Mapping", "Case Study Annotation", "Color-Coded Concept Sorting", "Guided Note Templates", "Reflective Quickwrites", "Vocabulary Concept Cards", "Think-Aloud Modeling for dense theoretical paragraphs"],
    "text_source": "CDA Council Texts; Conscious Discipline (Bailey); Developmental Theory & Practice Texts",
    "placement": "Texts integrate developmental theory, psychology, cognitive science, social-emotional frameworks, and practical guidance.",
    "image": "images/early_childhood_education.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Early_Childhood_Education_1.png, images/Program_Text_Examples_images/Early_Childhood_Education_2.png, images/Program_Text_Examples_images/Early_Childhood_Education_3.png"
  },
  "electronic_systems": {
    "name": "Electronic Systems Integration & Automation",
    "sector": "Manufacturing & Trades",
    "lexile": "1200L–1300L",
    "lexile_mid": 1250,
    "grade_band": "11–12",
    "cognitive_load": "High",
    "fast_ela": "Level 3+",
    "act": "19–22",
    "sat": "490–540",
    "barrier_pct": "40–50%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "High Gap",
    "main_challenge": "Combining technical theory, schematic interpretation, safety documentation, and procedural instructions. Must move fluidly between written explanations, diagrams, and manufacturer documentation.",
    "learning_profile": "Hands-on, mechanically minded, and pattern oriented. Benefit from seeing problems worked step-by-step. Strong procedural thinkers who may overlook conceptual reasoning.",
    "instructional_implications": "Students may copy formulas without conceptualizing relationships between voltage, current, resistance, and power. Instruction should emphasize prediction and real-world troubleshooting.",
    "strategies": ["Formula Annotation", "Dual Coding (equations + diagrams)", "Step-Sequenced Problem Walkthroughs", "Unit-Conversion Mapping", "Think-Aloud Calculations", "Error-Analysis Routines", "Prediction Prompts before solving"],
    "text_source": "Instructor-developed electrical theory modules (Ohm's Law, power, conversions)",
    "placement": "Best suited for students with moderate math fluency, ability to follow ordered steps, and comfort working with formulas.",
    "image": "images/electronic_systems_integration_automation.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Electronic_Systems_Integration_1.png, images/Program_Text_Examples_images/Electronic_Systems_Integration_2.png, images/Program_Text_Examples_images/Electronic_Systems_Integration_3.png"
  },
  "enterprise_desktop": {
    "name": "Enterprise Desktop and Mobile Support Technology",
    "sector": "Information Technology",
    "lexile": "1000L–1100L",
    "lexile_mid": 1050,
    "grade_band": "9.6",
    "cognitive_load": "High",
    "fast_ela": "Level 3",
    "act": "18–20",
    "sat": "480–520",
    "barrier_pct": "50–60%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "High Gap",
    "main_challenge": "Vendor documentation, troubleshooting trees. Dense with acronyms, conditional logic, and sequential instructions. Success depends on precision reading and following logical steps.",
    "learning_profile": "Methodical, systems-minded learners who like troubleshooting, logic puzzles, and figuring out how things work; prefer clear procedures and tangible outcomes.",
    "instructional_implications": "Students benefit from explicit modeling of technical reading — how to parse step-by-step instructions and identify conditions or exceptions.",
    "strategies": ["Think-Alouds while reading documentation", "Guided Note Templates for process logs", "Flowcharting to represent procedures"],
    "text_source": "A+ Core 1 and Core 2 CertMaster Learn",
    "placement": "Reading materials include troubleshooting guides, system documentation, and network configuration procedures.",
    "image": "images/enterprise_desktop_and_mobile_support_technology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Enterprise_Desktop_and_Mobile_S_1.gif"
  },
  "facials_specialty": {
    "name": "Facials Specialty",
    "sector": "Health & Beauty",
    "lexile": "1050L–1150L",
    "lexile_mid": 1100,
    "grade_band": "10–12",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "17–19",
    "sat": "460–520",
    "barrier_pct": "25–35%",
    "workforce_rating": 3,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Interpreting technical vocabulary accurately while applying it to hands-on treatments. Must distinguish between descriptive, instructional, and safety-related text.",
    "learning_profile": "Hands-on, detail-oriented, and comfort-driven practitioners who benefit from visually modeling procedures and understanding why each step matters.",
    "instructional_implications": "Learners may quickly grasp the 'how-to' steps but struggle with the underlying science, especially distinctions between positive and negative polarity, ion movement, and chemical reactions.",
    "strategies": ["Step-by-Step Walk-Throughs with Annotated Visuals", "Before/After Diagrams (ion movement/follicle changes)", "Vocabulary Mapping of technical terms", "Cloze-Reading Activities (polarity, chemical reactions)", "Safety-Scenario Reading Tasks", "Teach-Back Rotations"],
    "text_source": "Milady Standard Esthetics: Chapter 10 – Facial Devices and Technology",
    "placement": "Learners who struggle with vocabulary or conditional instructions may misinterpret steps, especially when polarity, pressure, or timing affect safety.",
    "image": "images/facials_specialty.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Facials_Specialty_1.jpg, images/Program_Text_Examples_images/Facials_Specialty_2.jpg,"
  },
  "heavy_equipment": {
    "name": "Heavy Equipment Service Technician",
    "sector": "Manufacturing & Trades",
    "lexile": "1180L–1300L",
    "lexile_mid": 1240,
    "grade_band": "12.5",
    "cognitive_load": "High",
    "fast_ela": "Level 4 or higher",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "40–50%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "High Gap",
    "main_challenge": "Advanced mechanical theory, system diagnostics, manufacturer service manuals, and safety documentation. Dense with conditional logic, schematics, and quantitative data.",
    "learning_profile": "Mechanically minded, systems-oriented learners who thrive on understanding how parts interact; strong in logical reasoning and spatial visualization.",
    "instructional_implications": "Learners often grasp the procedure but miss underlying theory. Requires managing dense mechanical and quantitative information.",
    "strategies": ["Concept-Before-Procedure Teaching", "Flow Diagram Construction", "Cloze Reading for formulas", "Peer Explanation Rotations"],
    "text_source": "HEST Year 2 digital curriculum (Turbocharger functions)",
    "placement": "Text combines advanced mechanical theory with quantitative reasoning. Vocabulary assumes familiarity with physics and combustion processes.",
    "image": "images/heavy_equipment_service_technician.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Heavy_Equipment_Service_Technic_1.png,"
  },
  "hvacr": {
    "name": "HVAC/R",
    "sector": "Manufacturing & Trades",
    "lexile": "1180L–1320L",
    "lexile_mid": 1250,
    "grade_band": "11–CCR",
    "cognitive_load": "High",
    "fast_ela": "Level 4",
    "act": "20–22",
    "sat": "520–560",
    "barrier_pct": "35–45%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "High Gap",
    "main_challenge": "Interpreting technical manuals, wiring diagrams, refrigeration cycle explanations, safety codes, and regulatory standards dense with conditional logic and formulas.",
    "learning_profile": "Mechanically minded problem-solvers who enjoy figuring out how systems behave. Strong in spatial reasoning and troubleshooting sequences. May avoid or rush written material.",
    "instructional_implications": "Students commonly grasp the procedure but miss the rationale. Instruction must deliberately slow the pace of reading tasks and consistently model how to extract meaning from diagrams.",
    "strategies": ["Concept-Before-Procedure Teaching", "Flow Diagrams for troubleshooting", "Dual-Coded Graphics for wiring/components", "Guided Cloze Notes for formulas/safety language", "Vocabulary Notebooks tied to real components", "Think-Aloud Modeling of manual interpretation", "Partner Read-and-Do Rotations"],
    "text_source": "Understanding and Implementing Starting Capacitors in Split Systems",
    "placement": "Learners with weak decoding or limited stamina for complex informational text often struggle during the first 150 hours.",
    "image": "images/hvacr.jpg", 
    "sample_image": "images/Program_Text_Examples_images/HVAC_R_1.png, images/Program_Text_Examples_images/HVAC_R_2.png, images/Program_Text_Examples_images/HVAC_R_3.png, images/Program_Text_Examples_images/HVAC_R_4.png, images/Program_Text_Examples_images/HVAC_R_5.png, images/Program_Text_Examples_images/HVAC_R_6.png, images/Program_Text_Examples_images/HVAC_R_7.png, images/Program_Text_Examples_images/HVAC_R_8.png"
  },
  "machining": {
    "name": "Machining Technologies (CNC)",
    "sector": "Manufacturing & Trades",
    "lexile": "1100L–1220L",
    "lexile_mid": 1160,
    "grade_band": "11.2",
    "cognitive_load": "High",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "45–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 8",
    "gap": "Significant Gap",
    "main_challenge": "Technical texts combine precision measurement, multi-step procedures, symbolic notation (G-code/M-code), and dense safety language where small errors can produce costly or dangerous outcomes.",
    "learning_profile": "Spatial-analytical learners who process information best through diagrams, repetition, and applied problem-solving; often prefer visual aids and step-by-step procedures.",
    "instructional_implications": "Students often read selectively or skip dense explanations. Teach how to interpret visuals as 'text.'",
    "strategies": ["Symbol Decoding Activities", "Visual Note-Taking", "Guided Problem Breakdown", "Collaborative Error Analysis"],
    "text_source": "Machine Trades Print Reading, G-W Publisher",
    "placement": "Sentences are concise but conceptually dense, requiring attention to tolerances, geometry, and schematic interpretation.",
    "image": "images/machining_technologies_cnc.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Machining_Technologies_(CNC)_1.png"
  },
  "marine_service": {
    "name": "Marine Service Technologies",
    "sector": "Transportation",
    "lexile": "1160L–1280L",
    "lexile_mid": 1220,
    "grade_band": "12.1",
    "cognitive_load": "High",
    "fast_ela": "Level 4",
    "act": "21–23",
    "sat": "540–580",
    "barrier_pct": "45–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Technical manuals integrating mechanical, electrical, fuel, and corrosion-control systems with dense procedural steps and safety warnings across multiple onboard systems.",
    "learning_profile": "Spatial and systems-based learners who grasp mechanical relationships intuitively; often hands-on and visual, needing real-time demonstration to anchor abstract text.",
    "instructional_implications": "Learners may skim for steps but miss critical safety or diagnostic reasoning embedded in text.",
    "strategies": ["Diagram Tracing with Concurrent Verbalization", "Safety Cue Highlighting", "Color-Coded Electrical Mapping", "Paired Reading between Text and Schematic", "'Explain Your Reasoning' Debriefs after lab procedures"],
    "text_source": "Yamaha Outboard Systems Manual and ABYC Marine Electrical Systems Manual",
    "placement": "Texts mix technical specifications, procedural steps, and conceptual electrical theory. Reading success depends on tolerance for detail and ability to visualize systems in 3D.",
    "image": "images/marine_service_technologies.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Marine_Service_Technologies_1.png, images/Program_Text_Examples_images/Marine_Service_Technologies_2.png, images/Program_Text_Examples_images/Marine_Service_Technologies_3.png"
  },
  "master_auto": {
    "name": "Master Automotive Service Technology",
    "sector": "Transportation",
    "lexile": "1100L–1220L",
    "lexile_mid": 1160,
    "grade_band": "11.3",
    "cognitive_load": "High",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "40–50%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 9",
    "gap": "Significant Gap",
    "main_challenge": "Interpreting complex diagnostic procedures, manufacturer service information, wiring diagrams, technical service bulletins, and safety documentation across mechanical, electrical, and computerized systems.",
    "learning_profile": "Mechanically analytical learners who connect concepts best through demonstration, repetition, and visualization of systems in motion.",
    "instructional_implications": "Students may memorize definitions without grasping how abstract forces translate to mechanical action.",
    "strategies": ["Diagram Analysis", "Analogical Reasoning (electricity to fluid flow)", "Guided Annotation of cause/effect statements", "Think-Do-Reflect Cycles linking readings to lab performance"],
    "text_source": "Fundamentals of Automotive Technology, CDX",
    "placement": "Texts integrate scientific reasoning, physics-based concepts, and applied systems language. Requires comfort with abstract cause-and-effect reasoning.",
    "image": "images/master_automotive_service_technology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Master_Automotive_Service_Techn_1.png"
  },
  "medical_assisting": {
    "name": "Medical Assisting",
    "sector": "Healthcare",
    "lexile": "1180L–1300L",
    "lexile_mid": 1240,
    "grade_band": "12.5",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 4+",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "35–45%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 10",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Texts blend medical terminology, anatomy and physiology, clinical procedures, patient documentation, and regulatory guidance.",
    "learning_profile": "Detail-oriented learners who thrive on structured, procedural tasks. Typically enjoy hands-on skill development and pattern recognition.",
    "instructional_implications": "Students may memorize steps without understanding underlying physiology. Instruction should reinforce cause-and-effect relationships between cardiac electrical activity and ECG waveforms.",
    "strategies": ["Annotated Diagram Reading", "Dual Coding (text + labeled ECG visuals)", "Vocabulary Mapping for conduction terms", "Step-Sequencing Exercises", "Think-Aloud Modeling during ECG interpretation", "Prediction Prompts", "Structured Error-Analysis Routines", "Procedural Retelling"],
    "text_source": "Fundamentals of Clinical Medical Assisting – Chapter 26 (Electrocardiography)",
    "placement": "Text is dense with medical terminology, anatomy/physiology concepts, and procedural descriptions requiring precise comprehension.",
    "image": "images/medical_assisting.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Medical_Assisting_1.png, images/Program_Text_Examples_images/Medical_Assisting_2.png, images/Program_Text_Examples_images/Medical_Assisting_3.png"
  },
  "nursing_assistant": {
    "name": "Nursing Assistant (Long-Term Care)",
    "sector": "Healthcare",
    "lexile": "1040L",
    "lexile_mid": 1040,
    "grade_band": "9–12",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3 or higher",
    "act": "18–20",
    "sat": "480–520",
    "barrier_pct": "25–35%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "N/A",
    "gap": "Significant Gap",
    "main_challenge": "Applying written care guidance accurately in fast-paced, human-centered care settings. Reading focuses on basic anatomy, patient care procedures, safety protocols, and infection control.",
    "learning_profile": "Learners benefit from clear models, repeated exposure to terminology, diagrams, and opportunities to verbalize care steps.",
    "instructional_implications": "Reading should be chunked to prevent overload, especially in sections containing multiple disorders or long lists of precautions.",
    "strategies": ["Vocabulary Mapping", "Diagram Labeling", "Sequential Retell of Procedures", "Dual Coding"],
    "text_source": "Mosby's Textbook for Nursing Assistants",
    "placement": "Procedural and descriptive text with focus on safety and empathy.",
    "image": "images/nursing_assistant_longterm_care.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Nursing_Assistant_(Long-Term_Care)_1.png, images/Program_Text_Examples_images/Nursing_Assistant_(Long-Term_Care)_2.png, images/Program_Text_Examples_images/Nursing_Assistant_(Long-Term_Care)_3.png"
  },
"Patient_Care_Technician": {
    "name": "Patient Care Technician",
    "sector": "Healthcare",
    "lexile": "1040L–1150L",
    "lexile_mid": 1095,
    "grade_band": "10.2",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "35–45%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 10",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Reading demands span multiple care domains including phlebotomy, EKG procedures, patient monitoring, and documentation. Must integrate written instructions across varied clinical tasks.",
    "learning_profile": "Empathetic, task-oriented learners who value clarity, hands-on learning, and real-world context; thrive on repetition, demonstration, and visual reinforcement.",
    "instructional_implications": "Students may complete tasks accurately but miss nuances of patient interaction or rationale behind steps.",
    "strategies": [
      "Step-by-Step Text Annotation",
      "'Why This Step Matters' Reflection Prompts",
      "Scenario-Based Reading (ethics + procedure)",
      "Color-Coded Vocabulary Logs",
      "Guided Simulations Combining Text with Practice"
    ],
    "text_source": "Hartman's Complete Guide for the Patient Care Technician (2024)",
    "placement": "Texts are procedural and highly structured, blending patient-centered ethics with technical instructions.",
    "image": "images/patient_care_technician.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Patient_Care_Technician_1.png, images/Program_Text_Examples_images/Patient_Care_Technician_2.png, images/Program_Text_Examples_images/Patient_Care_Technician_3.png"
},
"Pharmacy_Technician": {
    "name": "Pharmacy Technician",
    "sector": "Healthcare",
    "lexile": "1180L–1280L",
    "lexile_mid": 1230,
    "grade_band": "11–CCR",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 4",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "35–45%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 10",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Pharmacy law and ethics, medication classifications, dosage calculations, safety protocols. Dense with technical terminology and regulatory language where small reading errors carry significant safety implications.",
    "learning_profile": "Detail-oriented, rule- and procedure-driven, comfortable toggling between words, numbers, and symbols. Strong at memorizing lists but may treat rules as isolated facts.",
    "instructional_implications": "Students may misread small qualifiers in law/ethics passages ('except when…', 'unless…') or drop units/steps in dosage calculations.",
    "strategies": [
      "Guided Text Annotation of legal/pharmacology passages",
      "Structured Note Frames for laws/agency roles",
      "Concept Mapping for pharmacokinetics",
      "Worked-Example / Your-Turn Calculation Pairs",
      "Dimensional-Analysis Sentence Stems",
      "Close Reading of HIPAA/ethics scenarios",
      "Think-Aloud Modeling for error checking",
      "Calculation Logbooks with reflection",
      "Retrieval Practice with mixed-format questions"
    ],
    "text_source": "Mosby's Pharmacy Technician: Principles and Practice, 7e",
    "placement": "Students reading significantly below grade level or weak in math vocabulary will need intensive scaffolds.",
    "image": "images/pharmacy_technician.jpg" , 
    "sample_image": "images/Program_Text_Examples_images/Pharmacy_Technician_1.png, images/Program_Text_Examples_images/Pharmacy_Technician_2.png, images/Program_Text_Examples_images/Pharmacy_Technician_3.png"
},
"Phlebotomy": {
    "name": "Phlebotomy",
    "sector": "Healthcare",
    "lexile": "1120L–1180L",
    "lexile_mid": 1150,
    "grade_band": "10–12+",
    "cognitive_load": "Medium",
    "fast_ela": "Level 4 or high Level 3",
    "act": "20–23",
    "sat": "500–560",
    "barrier_pct": "25–35%",
    "workforce_rating": 4,
    "risk": "Medium–High",
    "fldoe_min": "N/A",
    "gap": "Significant Gap",
    "main_challenge": "Venous anatomy, collection procedures, infection control, safety protocols, specimen handling, and documentation. Translating written guidance into accurate, time-sensitive practice.",
    "learning_profile": "Concrete, procedural learners who thrive with demonstrations and visual models. Strong at hands-on skills but may initially struggle with invisible physiological processes.",
    "instructional_implications": "Students may memorize isolated terms rather than understanding system interactions. Instruction should emphasize sequence reasoning and visual mapping of processes.",
    "strategies": [
      "Sequence Mapping",
      "Diagram Annotation",
      "Dual Coding (text + clotting visuals)",
      "Vocabulary Mapping",
      "Cause-and-Effect Chains",
      "Think-Aloud Explanations during demonstrations",
      "Verbal Rehearsal of Procedural Steps"
    ],
    "text_source": "Hartman's Complete Guide for the Phlebotomy Technician: The Circulatory System",
    "placement": "Best suited for students with moderate reading fluency, comfort with scientific vocabulary, and ability to follow multi-step processes accurately.",
    "image": "images/phlebotomy.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Phlebotomy_1.png, images/Program_Text_Examples_images/Phlebotomy_2.png, images/Program_Text_Examples_images/Phlebotomy_3.png"
},
"Practical_Nursing": {
    "name": "Practical Nursing",
    "sector": "Healthcare",
    "lexile": "1180L–1320L",
    "lexile_mid": 1250,
    "grade_band": "12.9",
    "cognitive_load": "High",
    "fast_ela": "Level 4 or higher",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "45–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 11",
    "gap": "Moderate Gap",
    "main_challenge": "Anatomy and physiology, pharmacology, dosage calculations, care plans, and clinical protocols. Dense with medical terminology, cause-and-effect relationships, and conditional language.",
    "learning_profile": "Detail-oriented learners who connect scientific concepts to practical care; thrive in case-based examples and structured clinical reasoning.",
    "instructional_implications": "Students may focus on memorizing symptoms and protocols rather than understanding the physiology driving them.",
    "strategies": [
      "Annotated Clinical Reading (mechanism → symptom → intervention)",
      "Compare/Contrast Frames for similar conditions",
      "Diagram Labeling for physiological processes",
      "Think-Aloud Modeling for ATI passages",
      "Case-Based Summaries linking text to patient scenarios"
    ],
    "text_source": "ATI Nursing Fundamentals (Urinary Incontinence and Fluid/Electrolyte Balance)",
    "placement": "Text blends scientific explanation with clinical application. Success depends on understanding cause-and-effect relationships and conceptual transfer.",
    "image": "images/practical_nursing.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Practical_Nursing_1.png, images/Program_Text_Examples_images/Practical_Nursing_2.png, images/Program_Text_Examples_images/Practical_Nursing_3.png"
},
"Professional_Culinary_Arts_&_Hospitality": {
    "name": "Professional Culinary Arts & Hospitality",
    "sector": "Hospitality",
    "lexile": "1080L–1180L",
    "lexile_mid": 1130,
    "grade_band": "10–11",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "25–35%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Recipes, procedural instructions, safety and sanitation standards, menu planning, and hospitality guidelines. Translating written instructions into precise, time-sensitive execution.",
    "learning_profile": "Sensory, hands-on learners who synthesize reading with doing; thrive in structured demonstrations and real-world examples.",
    "instructional_implications": "Students may focus on memorizing recipes rather than understanding why ingredients behave as they do.",
    "strategies": [
      "Annotated Recipe Reading (highlight function of each step)",
      "T-Charting 'ingredient → purpose'",
      "Think-Aloud Modeling during demonstrations",
      "Sensory Recall Discussions linking theory to practice"
    ],
    "text_source": "Professional Cooking, 8th Edition",
    "placement": "Text blends technical precision with culinary artistry. Success depends on understanding sequence, measurement, and conceptual transfer.",
    "image": "images/professional_culinary_arts_hospitality.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Professional_Culinary_Arts_&_Ho_1.png, images/Program_Text_Examples_images/Professional_Culinary_Arts_&_Ho_2.png, images/Program_Text_Examples_images/Professional_Culinary_Arts_&_Ho_3.png"
},
"Proffesional_Nursing": {
    "name": "Professional Nursing",
    "sector": "Healthcare",
    "lexile": "1180L–1320L",
    "lexile_mid": 1250,
    "grade_band": "12.9",
    "cognitive_load": "High",
    "fast_ela": "Level 4 or higher",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "50–60%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 11",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Advanced anatomy and physiology, pharmacology, patient case studies, evidence-based practice, ethics, and regulatory standards. Must synthesize research findings and clinical guidelines.",
    "learning_profile": "Reflective learners with strong reading stamina, empathy, and ability to integrate scientific information with human context; thrive on real-world application.",
    "instructional_implications": "Texts require stamina and synthesis across long passages and data-heavy charts.",
    "strategies": [
      "Case-Based Reading",
      "Jigsaw Summarizing of textbook sections",
      "Terminology Flashcards",
      "Socratic Questioning about cause/effect in patient scenarios"
    ],
    "text_source": "Complex Case Study: Multiple Comorbidities with Head Trauma",
    "placement": "Texts combine scientific and clinical writing, requiring comprehension of anatomy, pharmacology, and ethical standards.",
    "image": "images/professional_nursing.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Professional_Nursing_1.jpg, images/Program_Text_Examples_images/Professional_Nursing_2.jpg, images/Program_Text_Examples_images/Professional_Nursing_3.jpg"
},
"Surgical_Technology": {
    "name": "Surgical Technology",
    "sector": "Healthcare",
    "lexile": "1130L–1250L",
    "lexile_mid": 1190,
    "grade_band": "11.0–12.5",
    "cognitive_load": "High",
    "fast_ela": "Level 3–4",
    "act": "20–22",
    "sat": "500–540",
    "barrier_pct": "45–55%",
    "workforce_rating": 5,
    "risk": "High",
    "fldoe_min": "Grade 11",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Surgical procedures, instrumentation, sterile technique, anatomy, and safety protocols. Dense with technical terminology, precise sequencing, and high-stakes conditional language.",
    "learning_profile": "Procedural, hands-on learners who think in steps, sequences, and visual models. Many excel at spatial interpretation of diagrams.",
    "instructional_implications": "Students tend to memorize lists without integrating the clinical significance. They may confuse similar concepts.",
    "strategies": [
      "Annotated Diagram Reading",
      "Sequence Mapping of procedures and anesthesia phases",
      "T-Charting (medical term → clinical relevance)",
      "Vocabulary Grouping by body system",
      "Scenario-Based Summarization tied to OR workflow",
      "Think-Aloud Modeling",
      "Chunk-and-Check Reading",
      "Cause-and-Effect Highlighting"
    ],
    "text_source": "MAVCC – Introduction to Surgical Technology (Anesthesia, Regional Blocks, Tissue Types)",
    "placement": "Cognitive load is significant because sections present hierarchical information (stages → sub-steps → cautions → complications).",
    "image": "images/surgical_technology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Surgical_Technology_1.png, images/Program_Text_Examples_images/Surgical_Technology_2.png, images/Program_Text_Examples_images/Surgical_Technology_3.png"
},
"Veterinary_Assisting": {
    "name": "Veterinary Assisting",
    "sector": "Agriculture & Animal Science",
    "lexile": "1250L–1400L",
    "lexile_mid": 1325,
    "grade_band": "11–CCR",
    "cognitive_load": "Medium–High",
    "fast_ela": "Level 4",
    "act": "22–24",
    "sat": "550–600",
    "barrier_pct": "30–40%",
    "workforce_rating": 4,
    "risk": "Medium–High",
    "fldoe_min": "Grade 9",
    "gap": "Moderate Gap",
    "main_challenge": "Animal anatomy and physiology, clinical procedures, medical terminology across multiple species. Must interpret descriptive and technical language with unfamiliar anatomical terms.",
    "learning_profile": "Analytically inclined, detail-oriented, comfortable with scientific classification and systems thinking. Highly motivated by animal care but may underestimate academic rigor.",
    "instructional_implications": "Without intentional scaffolding, students may memorize isolated facts without understanding functional relationships.",
    "strategies": [
      "Diagram Annotation",
      "Labeled Sketching",
      "Vocabulary Mapping with Morphology (roots/prefixes/suffixes)",
      "Chunked Guided Reading",
      "Compare-and-Contrast Charts (avian vs mammalian anatomy)",
      "Oral Retelling of System Functions",
      "Instructor Think-Alouds modeling dense scientific paragraphs"
    ],
    "text_source": "Avian Anatomy and Physiology instructional text",
    "placement": "Demands strong reading stamina, advanced decoding of anatomical terminology, and ability to mentally model complex internal systems.",
    "image": "images/veterinary_assisting.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Veterinary_Assisting.jpg, images/Program_Text_Examples_images/Veterinary_Assisting_2.png, images/Program_Text_Examples_images/Veterinary_Assisting_3.png"
}, 
"Welding_Technology": {
    "name": "Welding Technology",
    "sector": "Manufacturing & Trades",
    "lexile": "1120L–1250L",
    "lexile_mid": 1185,
    "grade_band": "11.7",
    "cognitive_load": "Medium",
    "fast_ela": "Level 3–4",
    "act": "19–21",
    "sat": "500–540",
    "barrier_pct": "30–40%",
    "workforce_rating": 4,
    "risk": "Medium",
    "fldoe_min": "Grade 9",
    "gap": "Moderate to Significant Gap",
    "main_challenge": "Interpreting technical safety standards, welding symbols, procedure specifications (WPS), and equipment manuals relying on dense terminology and visual-text integration.",
    "learning_profile": "Spatial and tactile learners who prefer learning by doing; excel with visual examples, demonstrations, and sequential technical instructions.",
    "instructional_implications": "Information is procedural and visual-spatial, often with abstract reference to unseen forces. Learners may misinterpret text-only instructions.",
    "strategies": [
      "Photo Annotation",
      "Dual Coding (text + visual)",
      "Procedural Retelling",
      "Verbal Rehearsal before hands-on performance"
    ],
    "text_source": "American Welding Society (2023)",
    "placement": "Success hinges on spatial reasoning and applied reading comprehension rather than literary analysis.",
    "image": "images/welding_technology.jpg", 
    "sample_image": "images/Program_Text_Examples_images/Welding_Technology_1.png, images/Program_Text_Examples_images/Welding_Technology_2.png, images/Program_Text_Examples_images/Welding_Technology_3.png"
}
};